### PR TITLE
#10 fix make docker

### LINKED ISSUE #10: make docker won't work (CGO_ENABLED should be 0)
The Docker image generated with `make docker` won't work as it is based on alpine:

```
make docker
echo '{\n "url": "git:git@github.com:zalando-incubator/postgres-operator.git",\n "revision": "f635fac",\n "author": "hjacobs",\n "status": ""\n}' > scm-source.json
mkdir -p docker/build/
cp build/linux/postgres-operator scm-source.json docker/build/
cd docker && docker build --rm -t "pierone.example.com/acid/postgres-operator:f635fac" .
Sending build context to Docker daemon  49.23MB
Step 1 : FROM alpine
 ---> 02674b9cb179
Step 2 : MAINTAINER Team ACID @ Zalando <team-acid@zalando.de>
 ---> Using cache
 ---> 7b9b7535d5a5
Step 3 : RUN apk --no-cache add ca-certificates
 ---> Using cache
 ---> 9b87d980f206
Step 4 : COPY build/* /
 ---> de51ed941534
Removing intermediate container 8b9ef9592485
Step 5 : ENTRYPOINT /postgres-operator
 ---> Running in 2b9976b1d602
 ---> 1dcb57fa2d2f
Removing intermediate container 2b9976b1d602
Successfully built 1dcb57fa2d2f
```

Docker container cannot start:
```
docker run -it pierone.example.com/acid/postgres-operator:f635fac
docker: Error response from daemon: Container command '/postgres-operator' not found or does not exist.
```

The required libraries do not exist:
```docker run -it --entrypoint sh pierone.example.com/acid/postgres-operator:f635fac
/ # ldd /postgres-operator 
	/lib64/ld-linux-x86-64.so.2 (0x55a7b360a000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x55a7b360a000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x55a7b360a000)
/ # ls -la /lib64
ls: /lib64: No such file or directory
```

### PR DESCRIPTION
**Pull request by hjacobs**
Fixes #10

### CODE REVIEW

**Comment by hjacobs** [comment]
I also did:

```
IMAGE=registry-write.opensource.zalan.do/acid/postgres-operator make docker
IMAGE=registry-write.opensource.zalan.do/acid/postgres-operator make push
docker run -it registry.opensource.zalan.do/acid/postgres-operator:8c7becc
2017/05/14 16:00:01 Spilo operator 946f623-dirty

**Comment by hjacobs** [comment]
Only after this change I could get the complete README instructions to work (with Minikube).

**Comment by hjacobs** [comment]
:+1:

**Comment by ikitiki** [comment]
LGTM

**Comment by ikitiki** [comment]
👍

**Pull request merged**
