### PR TITLE
Make env var overwrite configmap setting for watching namespaces 

### LINKED ISSUE #222: Make env var overwrite configmap setting for watching namespaces

### PR DESCRIPTION
**Pull request by zerg-junior**
Closes #222

### CODE REVIEW

**Comment by zerg-junior** [comment]
This PR does two things:
1. streamlines and documents the current - aka 'no watching of multiple namespaces'  - usage of the `watched_namespace` setting 
2. enables overwriting of the setting by an operator pod's env  variable of the same name

**Comment by Jan-M** [comment]
:+1:

**Comment by zerg-junior** [comment]
:+1:

**Comment by mgomezch** [comment]
:+1:

**Pull request merged**
